/**********************************
 * main file for testing purposes *
 **********************************/

#include "test.h"

int main() {
  /* TEST(DECIMAL_FLAG_ZERO); */
  /* TEST(DECIMAL_FLAG_MINUS); */
  /* TEST(DECIMAL_FLAG_MINUSZERO); */
  /* TEST(DECIMAL_PRECISION); */
  /*  TEST(DECIMAL_PRECISION_NULL); */
  /* TEST(DECIMAL_FLAG_ZERO_PRECISION); */
  /* TEST(DECIMAL_FLAG_ZERO_PRECISION_NULL); */
  /* TEST(DECIMAL_FLAG_MINUS_PRECISION); */
  /* TEST(DECIMAL_WIDTH_ASTERISK) */

TEST(DECIMAL_WIDTH);
TEST(DECIMAL_MINUS);
TEST(DECIMAL_PLUS);
TEST(DECIMAL_SPACE);
TEST(DECIMAL_ZERO);
TEST(DECIMAL_MINUS_PLUS);
TEST(DECIMAL_MINUS_SPACE);
TEST(DECIMAL_PLUS_ZERO);
TEST(DECIMAL_SPACE_ZERO);
  /* TEST(HEXA_PRECISION); */
  /* TEST(HEXA_FLAG_MINUS_PRECISION); */
  /* TEST(HEXA_FLAG_HASH_PRECISION); */
  /* TEST(HEXA_FLAG_MINUS_HASH_PRECISION) */

  /* TEST(STR_WIDTH_LESS); */
  /* TEST(STR_WIDTH_MORE); */
  /* TEST(STR_FLAG_MINUS); */
  /* TEST(STR_WIDTH_PRECISION); */
  /* TEST(STR_PRECISION_LESS); */
  /* TEST(STR_PRECISION_MORE); */
  /* TEST(STR_PRECISION_NULL); */
  /* TEST(STR_PRECISION_ZERO); */

  /* TEST(C_WIDTH_MORE); */
  /* TEST(C_FLAG_MINUS); */

	// TEST(P_FLAG_MINUS);
	// TEST(P_WIDTH);

  return 0;
}
